language: python
sudo: false

install:
  - pip install --upgrade pip tox

script:
  - tox -e py27
  - (cd core && tox -e py27)
  - (cd bigtable && tox -e py27)
  - (cd storage && tox -e py27)
  - tox -e py34
  - (cd core && tox -e py34)
  - (cd bigtable && tox -e py34)
  - (cd storage && tox -e py34)
  - tox -e lint
  - tox -e cover
  - (cd core && tox -e cover)
  - (cd bigtable && tox -e cover)
  - (cd storage && tox -e cover)
  - tox -e system-tests
  - tox -e system-tests3
  - scripts/update_docs.sh

after_success:
  - tox -e coveralls

cache:
  directories:
    - ${HOME}/.cache/pip
