language: python
sudo: false

install:
  - pip install --upgrade pip tox

script:
  - python2.7 scripts/run_unit_tests.py
  - python3.4 scripts/run_unit_tests.py
  - python scripts/run_unit_tests.py --tox-env cover
  - tox -e lint
  - tox -e system-tests
  - tox -e system-tests3
  - scripts/update_docs.sh

after_success:
  - tox -e coveralls

cache:
  directories:
    - ${HOME}/.cache/pip
